config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'tweets#index'
  resources :tweets do 
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do 
      get 'search'
      get 'spot'
      get 'gourmet'
    end 
  end 
  resources :users, only: [:show, :edit, :update] 
  
  get "/users/:id/likes" => "users#likes"
  get "/users/:id/spot" => "users#spot"
  get "/users/:id/gourmet" => "users#gourmet"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    {id: 0, name: 'カテゴリーを選択してください'},{id: 1, name: 'gourmet'},{id: 2, name: 'spot'}
  ]
  include ActiveHash::Associations
  has_many :tweets
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :tweet
  belongs_to :user
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  validates :hashname, presence: true, length: { maximum: 50 }
  has_many :tweet_hashtags, dependent: :destroy
  has_many :tweets, through: :tweet_hashtags
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :user_id, presence: true
  validates :tweet_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  validates :text, presence: true
  validates :image, presence: true
  validates :category_id, presence: true
  
  belongs_to :user
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :tweet_hashtags, dependent: :destroy
  has_many :hashtags, through: :tweet_hashtags

  mount_uploader :image, ImageUploader

  def self.search(search)
    if search 
      Tweet.where('text LIKE(?)', "%#{search}%")
    else  
      Tweet.all 
    end  
  end
end

app/models/tweet_hashtag.rb
class TweetHashtag < ApplicationRecord
  belongs_to :tweet
  belongs_to :hashtag
  validates :tweet_id, presence: true
  validates :hashtag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, presence: true 

  has_many :tweets 
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet

  mount_uploader :user_image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    respond_to do |format|
      format.html { redirect_to tweet_path(params[:tweet_id])  }
      format.json
    end
  end

  private
  def comment_params 
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_tweet

  def create
    @like = Like.create(user_id: current_user.id, tweet_id: @tweet.id)
  end

  def destroy
    @like = current_user.likes.find_by(tweet_id: @tweet.id)
    @like.destroy
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search, :gourmet, :spot]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to root_path
      flash[:notice] = "投稿しました"
    else  
      render :new
    end 
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end

  def edit 
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to tweet_path 
    else  
      render :edit 
    end
  end 

  def show 
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end 

  def search 
    @tweets = Tweet.search(params[:keyword])
  end 

  def gourmet
    @tweets = Tweet.includes(:user).where(category_id: 1).order("created_at DESC")
  end

  def spot
    @tweets = Tweet.includes(:user).where(category_id: 2).order("created_at DESC")
  end


  

  private
  def tweet_params
    params.require(:tweet).permit(:image, :text, :category_id).merge(user_id: current_user.id)
  end 

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end 

  def move_to_index 
    unless user_signed_in?
      redirect_to action: :index 
    end 
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :likes]

  def show
    @user = User.find(params[:id]) 
    @tweets = @user.tweets.order("created_at DESC") 
    @nickname = @user.nickname 
    @profile = @user.profile 
    @count = @user.tweets.count
    @image = @user.user_image
  end 

  def edit
    @user = User.find(params[:id])    
  end 

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Profileを更新しました"
      redirect_to user_path
    else 
      render :edit 
    end
  end

  def likes
    @user = User.find_by(id: current_user.id) 
    @likes = Like.where(user_id: @user.id) 
    @nickname = @user.nickname 
    @profile = @user.profile 
    @count = @user.tweets.count
    @image = @user.user_image
  end

  def gourmet
    @user = User.find(params[:id]) 
    @tweets = @user.tweets.where(category_id: 1).order("created_at DESC") 
    @nickname = @user.nickname 
    @profile = @user.profile 
    @count = @user.tweets.count
    @image = @user.user_image
  end

  def spot
    @user = User.find(params[:id]) 
    @tweets = @user.tweets.where(category_id: 2).order("created_at DESC") 
    @nickname = @user.nickname 
    @profile = @user.profile 
    @count = @user.tweets.count
    @image = @user.user_image
  end

  private 

  def user_params 
    params.require(:user).permit(:nickname, :email, :user_image, :profile)
  end 

  def ensure_correct_user
    if current_user.id != params[:id].to_i
      redirect_to user_path 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert 
    %ul 
      -model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Discover
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' 
    -# = javascript_include_tag 'application'

  %body
    .Header
      .Header-left 
        =link_to root_path, class: "Header-left__title",  data: {"turbolinks"=>false} do 
          Discover 
      .Header-right
        = form_with(url: search_tweets_path, local: true, method: :get, class: "search-form") do |form|
          = form.text_field :keyword, placeholder: "キーワードを入力", class: "search-input"
          %button{type: "submit", class: "search-btn"}
            %i.fas.fa-search 
            

        - if user_signed_in?
          
          .Header-right__search-btn 
            =icon('fas', 'search')
          .Header-right__new-btn
            =link_to new_tweet_path, class: "Header-right__new-btn__link", data: {"turbolinks"=>false} do
              =icon('fas', 'plus')
          .Header-right__user-btn 
            =icon('fas', 'user-circle')
        - else 
          .Header-right__search-btn 
            =icon('fas', 'search')
          .Header-right__user-btn
            =icon('fas', 'user-circle')
    .Flash-message
      = flash[:notice]
    = yield

app/views/likes/_like.html.haml
- if Like.find_by(user_id: current_user.id, tweet_id: @tweet.id)
  = link_to "/tweets/#{@tweet.id}/likes/#{@tweet.likes.ids}", method: :delete, class: "element", remote: true do 
    = icon("fas", "heart", class: "like")
- else 
  = link_to "/tweets/#{@tweet.id}/likes", method: :post, class: "element", remote: true do 
    = icon("far", "heart", class: "unlike")
.count 
  = @tweet.likes.length

app/views/likes/create.js.erb
$("#like_<%= @tweet.id %>").html("<%= j(render 'likes/like') %>");

app/views/likes/destroy.js.erb
$("#like_<%= @tweet.id %>").html("<%= j(render 'likes/like') %>");

app/views/tweets/_dropdown.html.haml
.Dropdown
  - if user_signed_in?
    %ul.Doropdown__lists
      %li 
        = current_user.nickname 
        さん
      %li 
        = link_to user_path(current_user.id), data: {"turbolinks"=>false} do 
          My page
      %li
        =link_to destroy_user_session_path, data: {"turbolinks"=>false}, method: :delete do 
          Log out
  - else 
    %ul.Dropdown__lists 
      %li 
        = link_to new_user_registration_path, data: {"turbolinks"=>false} do 
          Sign in 
      %li 
        = link_to user_session_path, data: {"turbolinks"=>false} do 
          Log in

app/views/tweets/_top.html.haml
.Container
  .Top-container 
    .Top-container__messages
      %h2.Top-container__messages--message
        旅の過程にこそ価値がある。
      %p.Top-container__messages--name
        スティーブ・ジョブズ
  .Main-container
    %h1.Main-container__title 
      Posts List
    
    .Main-container__posts
      .Category 
        = link_to gourmet_tweets_path, class: "Category__gourmet ", data: {"turbolinks"=>false} do 
          Gourmet
        = link_to spot_tweets_path, class: "Category__spot ", data: {"turbolinks"=>false} do 
          Spot 
      .Post-new 
        .Post-new__images
          - @tweets.each do |tweet|
            .Post-new__images__image
              = link_to tweet_path(tweet.id), data: {"turbolinks"=>false}, method: :get do 
                %img{ src: tweet.image.url, alt: "写真１", class: "Post-new__images__image__photo"}
               
          

          
        
          
            

app/views/tweets/create.html.haml
.Contents
  = render "dropdown"
  .Container
    .Create 
      .Create__messages 
        %h1.Create__messages--message 
          投稿が完了しました  
        
        =link_to root_path,data: {"turbolinks"=>false}, class: "Create__messages--send" do 
          投稿一覧へ戻る

app/views/tweets/destroy.html.haml
.Contents 
  = render "dropdown"
  .Container 
    .Delete
      .Delete__messages 
        %h1.Delete__messages--message 
          投稿が削除されました 
        
        =link_to root_path, data: {"turbolinks"=>false}, class: "Delete__messages--send" do 
          投稿一覧へ戻る

app/views/tweets/edit.html.haml
.Contents
  = render "dropdown"
  .Container 
    .Edit-post 
      = form_with(model: @tweet, local: true, class: "Edit-post__form") do |form|
        %h3.Edit-post__form--title
          編集
        = render "layouts/error_messages", model: form.object
        = form.file_field :image, placeholder: "Image", class: "Edit-post__form--image" 
        = form.collection_select :category_id, Category.all, :id, :name
        = form.text_area :text, placeholder: "text", class: "Edit-post__form--text"
        = form.submit "SEND", class: "Edit-post__form--send"

      %p.Edit-post__share
        さぁ、旅に出ようか

app/views/tweets/gourmet.html.haml
.Contents
  = render "dropdown"
  = render "top"

app/views/tweets/index.html.haml
.Contents
  = render "dropdown"
  = render "top"

app/views/tweets/new.html.haml
.Contents
  = render "dropdown"
  .Container
    .New-post 
      = form_with(model: @tweet, local: true, class: "New-post__form") do |form|
        %h3.New-post__form--title
          新規投稿
        = render "layouts/error_messages", model: form.object
        = form.file_field :image, placeholder: "Image", class: "New-post__form--image" 
        = form.collection_select :category_id, Category.all, :id, :name
        = form.text_area :text, placeholder: "text", class: "New-post__form--text"
        = form.submit "SEND", class: "New-post__form--send"

      %p.New-post__share
        自分が見つけた光景を
        %br 
        みんなにシェアしましょう。
       

app/views/tweets/search.html.haml
.Contents 
  = render "dropdown"
  .Container 
    .Main-container
      %h1.Main-container__title 
        Posts List
      
      .Main-container__posts
        .Category 
          = link_to "#", class: "Category__gourmet " do 
            Gourmet
          = link_to "#", class: "Category__spot " do 
            Spot 
        .Post-new 
          .Post-new__images
            - @tweets.each do |tweet|
              .Post-new__images__image
                = link_to tweet_path(tweet.id), method: :get do 
                  %img{ src: tweet.image, alt: "写真１", class: "Post-new__images__image__photo"}

app/views/tweets/show.html.haml
.Contents 
  = render "dropdown"
  .Container
    .Show-post
      = link_to user_path(@tweet.user_id), data: {"turbolinks"=>false}, class: "Show-post__users" do
        - if @tweet.user.user_image.url.nil?
          = image_tag "user-icon.png", alt: "ユーザー", class: "Show-post__users--icon"
        - else
          = image_tag  @tweet.user.user_image.url, alt: "写真１", class: "Show-post__users--icon"
        %p.Show-post__users--name 
          = @tweet.user.nickname

      %img{ src: @tweet.image, alt: "写真１", class: "Show-post__image"} 

      .Show-post__contents 
        .Show-post__contents__like-btn 
          - if user_signed_in?
            .Like#like{ id: @tweet.id}
              = render "likes/like"
        .Show-post__contents__list 
          - if user_signed_in? && current_user.id == @tweet.user_id
            = link_to edit_tweet_path(@tweet.id), data: {"turbolinks"=>false}, class: "Show-post__contents__list__edit" do 
              Edit

            = link_to tweet_path(@tweet.id), data: {"turbolinks"=>false}, method: :delete, class: "Show-post__contents__list__destroy" do 
              Delete
              

      .Show-post__text 
        .Show-post__text__box 
          = @tweet.text

    .Comments
      - if current_user
        = form_with model: [@tweet, @comment], local: true, id: "new_comment" do |f|
          = f.text_area :text, placeholder: "コメントを追加...", rows: "3", class: "textbox"
          = f.submit "投稿する", class: "form__submit"
      - else 
        .need-login
          *** コメントの投稿・いいねには新規登録/ログインが必要です ***
      .lists
        - if @comments
          - @comments.each do |comment|
            .list 
              .list__name
                = link_to user_path(comment.user_id), data: {"turbolinks"=>false} do
                  = "#{comment.user.nickname} :"
              .list__text
                = comment.text


          
          

app/views/tweets/spot.html.haml
.Contents
  = render "dropdown"
  = render "top"

app/views/tweets/update.html.haml
.Contents
  = render "dropdown"
  .Container 
    .Update
      .Update__messages 
        %h1.Update__messages--message 
          投稿が更新されました 
        
        =link_to root_path, data: {"turbolinks"=>false}, class: "Update__messages--send" do 
          投稿一覧へ戻る

app/views/users/_show.html.haml
.Container 
  .Top
    .Top__user
      - if @user.user_image?
        = image_tag  @user.user_image.url, alt: "写真１", class: "Top__user__image"          
      - else
        = image_tag "user-icon.png", alt: "ユーザー", class: "Top__user__image"
      .Top__user__profile
        .Top__user__profile__name
          = @nickname
          %span/
          Number of posts: 
          = @count
        - if user_signed_in? && current_user.id.to_s == params[:id]
          = link_to  edit_user_path, data: {"turbolinks"=>false}, class: "Top__user__profile__prof" do 
            ProfileEdit
            = icon('fas', 'cog')
        .Top__user__profile__text 
          = @profile

  .Main
    %h1.Main__title 
      Posts List

    .Category 
      .Category-left
        = link_to "/users/#{@user.id}/gourmet", class: "Category__gourmet ", data: {"turbolinks"=>false} do 
          Gourmet
        = link_to "/users/#{@user.id}/spot", class: "Category__spot ", data: {"turbolinks"=>false} do 
          Spot 
        - if user_signed_in? && current_user.id.to_s == params[:id]
          = link_to "/users/#{@user.id}/likes", class: "Category__like", data: {"turbolinks"=>false} do 
            Like
    .Post-user
      .Post-user__images
        - @tweets.each do |tweet|
          .Post-user__images__image
            = link_to tweet_path(tweet.id), data: {"turbolinks"=>false}, method: :get do 
              %img{ src: tweet.image, alt: "写真１", class: "Post-user__images__image__photo"}

app/views/users/edit.html.haml
.Account 
  = render "tweets/dropdown"
    
  .Account-background 
    = image_tag "avenue-3464777_1920.jpg", alt: "写真", class: "Account-background__image"
  .Account-user
    - if current_user.user_image?
      = image_tag current_user.user_image.url, alt: "写真１", class: "Account-user__image"
    - else
      = image_tag "user-icon.png", alt: "ユーザー", class: "Account-user__image"
    .Account-user__name 
      = current_user.nickname
    .Account-user__count 
      Number of posts:
      = current_user.tweets.count

  .Account-edit 
    .title-block__first
    .title-block__second
      AccountEdit
    .title-block__third

  .Account-form
    = form_with(model: @user, multipart: true, local: true, class: "Form") do |f|
      .Form_error 
        = render "layouts/error_messages", model: @user
      .Form__field
        = f.label :nickname 
        %br/
        = f.text_field :nickname, autofocus: true 
      .Form__field
        = f.label :email  
        %br/
        = f.email_field :email, autofocus: true, autocomplete: "email"
      .Form__field       
        = f.label :Image 
        %br/
        .Form__image
          = f.file_field :user_image, placeholder: "Image", class: "Form__image__img"
      .Form__field
        =f.label :profile
        %br/
        = f.text_area :profile, placeholder: "your profile", class: "Form__profile"

      = f.submit "SEND", class: "Form__submit"


    
      

app/views/users/gourmet.html.haml
.Contents 
  = render "tweets/dropdown"
  = render "show"

app/views/users/likes.html.haml
.Contents 
  = render "tweets/dropdown"
  .Container 
    .Top
      .Top__user
        - if @user.user_image?
          = image_tag  @user.user_image.url, alt: "写真１", class: "Top__user__image"          
        - else
          = image_tag "user-icon.png", alt: "ユーザー", class: "Top__user__image"
        .Top__user__profile
          .Top__user__profile__name
            = @nickname
            %span/
            Number of posts: 
            = @count
          - if user_signed_in? && current_user.id.to_s == params[:id]
            = link_to  edit_user_path, data: {"turbolinks"=>false}, class: "Top__user__profile__prof" do 
              ProfileEdit
              = icon('fas', 'cog')
          .Top__user__profile__text 
            = @profile

    .Main
      %h1.Main__title 
        Posts List

      .Category 
        .Category-left
          = link_to "/users/#{@user.id}/gourmet", class: "Category__gourmet " do 
            Gourmet
          = link_to "/users/#{@user.id}/spot", class: "Category__spot " do 
            Spot 
          = link_to "/users/#{@user.id}/likes", class: "Category__like", data: {"turbolinks"=>false} do 
            Like
      .Post-user
        .Post-user__images
          - @user.like_tweets.each do |tweet|
            .Post-user__images__image
              = link_to tweet_path(tweet.id), data: {"turbolinks"=>false}, method: :get do 
                %img{ src: tweet.image, alt: "写真１", class: "Post-user__images__image__photo"}

app/views/users/show.html.haml
.Contents 
  = render "tweets/dropdown"
  = render "show"

app/views/users/spot.html.haml
.Contents 
  = render "tweets/dropdown"
  = render "show"